import jwt
from typing import Annotated
from fastapi import Depends, HTTPException
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select

from app.core.config import settings
from app.core.database import get_db
from app.models.user import User, RoleEnum

security = HTTPBearer()

def decode_supabase_token(token: str) -> dict:
    """Verifies and decodes JWT generated by Supabase Auth"""
    try:
        payload = jwt.decode(
            token,
            settings.SUPABASE_JWT_SECRET,
            algorithms=["HS256"],
            audience="authenticated"
        )
        return payload
    except jwt.ExpiredSignatureError:
        raise HTTPException(status_code=401, detail="Token has expired")
    except jwt.InvalidTokenError:
        raise HTTPException(status_code=401, detail="Invalid token")

async def get_current_user(
    credentials: Annotated[HTTPAuthorizationCredentials, Depends(security)],
    db: AsyncSession = Depends(get_db)
) -> User:
    """Extracts user from Supabase JWT and retrieves from DB"""
    token = credentials.credentials
    payload = decode_supabase_token(token)
    user_id = payload.get("sub")
    
    if not user_id:
        raise HTTPException(status_code=401, detail="Invalid token payload")
        
    result = await db.execute(select(User).where(User.id == user_id))
    user = result.scalar_one_or_none()
    
    if not user:
        raise HTTPException(status_code=401, detail="User not found in database")
        
    return user

async def require_premium(user: Annotated[User, Depends(get_current_user)]) -> User:
    """RBAC Guard for Premium endpoints"""
    if user.role not in (RoleEnum.PREMIUM, RoleEnum.ADMIN):
        raise HTTPException(status_code=403, detail="Premium subscription required")
    return user
